FROM node:20-buster-slim

RUN apt-get -y update \
    && apt-get install -y git
RUN mkdir /app

RUN yarn global add react
RUN yarn global add next
WORKDIR /app

ENV NODE_PATH /app/node_modules/

COPY ./client/package*.json ./

ADD ./client ./

RUN yarn install

EXPOSE 3000

CMD ["yarn", "run", "dev"]
